# 数据分析及处理

## 1. 商品数据

In [1]:
import pandas as pd

chunk_size = 500000 # 每一块的行数
chunks = []

for chunk in pd.read_csv('D:\\Datas\\tianchi_2014001_rec_tmall_product\\tianchi_2014001_rec_tmall_product.txt', sep="", chunksize=chunk_size):
    # 处理每个chunk的数据
    chunks.append(chunk)
    
# 合并chunk回一个大的DataFrame（如果需要的话）
product = pd.concat(chunks, axis=0)

In [2]:
import pandas as pd
from IPython.display import display, HTML

# 定义列名列表
column_names = ['item_id', 'title', 'pict_url','category', 'brand_id', 'seller_id']

# 设置DataFrame列名
product.columns = column_names

# 选择前10行数据
first_ten_rows = product.head(5)

# 为带滚动条的DataFrame横向展示设置CSS
styles = """
<style>
.scrollable_dataframe {
    max-height: 300px;
    overflow-x: auto;
    white-space: nowrap;
}
th {
    font-size: 14px;
}
td {
    font-size: 14px;
}
</style>
"""

# 生成带滚动条的DataFrame HTML
scrollable_df_html = f'<div class="scrollable_dataframe">{first_ten_rows.to_html()}</div>'

# 将CSS样式和HTML DataFrame包装在一起
html_output = styles + scrollable_df_html

# 在Jupyter Notebook中显示带滚动条的DataFrame
display(HTML(html_output))

通过分析和实践发现海量的数据对页面的渲染带来了不小的加载压力，因此考虑对商品表采取分割的方式，依据item_id截取前10万的数据。同理其他两个表页也采取item_id截取1-100000的数据，这样既使得存在关联的数据保存，也能保证数据量

In [22]:
sorted_df = product.sort_values(by='item_id')[:100000]

In [23]:
sorted_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100000 entries, 7116193 to 505633
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   item_id    100000 non-null  int64
 1   title      100000 non-null  object
 2   pict_url   99999 non-null   object
 3   category   100000 non-null  object
 4   brand_id   75264 non-null   object
 5   seller_id  100000 non-null  object
dtypes: int64(1), object(5)
memory usage: 5.3+ MB

In [25]:
import pandas as pd
# 假设 sorted_df 是您的DataFrame

# 设置显示所有列
pd.set_option('display.max_columns', None)

# 设置显示所有行
pd.set_option('display.max_rows', None)

# 显示 sorted_df 的前5行，每行完整展示
print(sorted_df.head(5))

         item_id                                              title  \
7116193        1  韩 惑   2013 秋装 新款   韩国进口 女装   圆领 下摆 条纹 蓬松 连衣裙  ...
3311479        2      车 品 世家   进口 大众 EOS 专用后备箱垫 汽车尾箱垫 皮革 行李箱垫 超 耐磨
1345145        3    2013 秋冬季 新款 女士 黑色短裙 半身裙   烫钻 加 长裙 大码 裙 胖 mm 裙子
6471956        4      花 画饰 界 高档 现代 简约 摄影 马 客厅 玄关 中 欧式 电表箱 有框装饰画 新品
5470584        5  吉 香 居 【 210 风味豆豉 】 拌饭   拌面酱   调味品   豉 香 浓郁   四...

                                                  pict_url category brand_id  \
7116193  http://img01.taobaocdn.com/bao/uploaded/i3/132...  10-2787   b39336
3311479  http://img01.taobaocdn.com/bao/uploaded/i3/132...  84-7351   b12875
1345145  http://img01.taobaocdn.com/bao/uploaded/i4/176...  10-4579   b85983
6471956  http://img01.taobaocdn.com/bao/uploaded/i1/154...   17-502   b25261
5470584  http://img01.taobaocdn.com/bao/uploaded/i1/151...  22-1244   b58958

        seller_id
7116193    s31710
3311479    s76755
1345145    s55371
6471956    s59900
5470584    s64125

In [16]:
sorted_df.to_csv('D:\\Datas\\datas\\product.csv', index=False)

## 2. 用户行为数据

In [17]:
#action数据太过庞大采取逐行读取三个大表的数据文件，筛选出 item_id 在 1 到 1000000 范围内的数据，并将结果写入到一个输出文件中
output_file = open('D:\\Datas\\datas\\df_action.txt', 'w')
file_paths = ['D:\\Datas\\tianchi_2014002_rec_tmall_log.parta\\tianchi_2014002_rec_tmall_log_parta.txt',
              'D:\\Datas\\tianchi_2014002_rec_tmall_log.partb\\tianchi_2014002_rec_tmall_log_partb.txt',
              'D:\\Datas\\tianchi_2014002_rec_tmall_log.partc\\tianchi_2014002_rec_tmall_log_partc.txt']


for file_path in file_paths:
    with open(file_path, 'r') as file:
        for line in file:
            # 假设每行数据格式为 "item_idother_columns"
            data_fields = line.strip().split('')
            item_id = int(data_fields[0])

            if 1 <= item_id <= 1000000:
                output_file.write(line)

output_file.close()

In [18]:
import pandas as pd

chunk_size = 500000 # 每一块的行数
chunks_1 = []

for chunk in pd.read_csv('D:\Datas\\datas\\df_action.txt', sep="", chunksize=chunk_size):
    # 处理每个chunk的数据
    chunks_1.append(chunk)
    
# 合并chunk回一个大的DataFrame（如果需要的话）
action = pd.concat(chunks_1, axis=0)

# 定义列名列表
column_names = ['item_id', 'user_id', 'action','vtime']

# 设置DataFrame列名
action.columns = column_names

In [19]:
action.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162216759 entries, 0 to 162216758
Data columns (total 4 columns):
 #   Column   Dtype
---  ------   -----
 0   item_id  int64
 1   user_id  object
 2   action   object
 3   vtime    object
dtypes: int64(1), object(3)
memory usage: 4.8+ GB

In [21]:
sorted_action = action.sort_values(by='item_id')

In [24]:
sorted_action.head(500)

           item_id    user_id action                vtime
35292346         1   u1144920  click  2013-09-18 22:34:26
157398286        1  u13739929  click  2013-09-26 23:30:28
55279005         1   u9989957  click  2013-09-26 23:27:55
99853140         1   u4722735  click  2013-09-14 21:21:27
129934202        1   u5379171  click  2013-09-18 00:16:23
...            ...        ...    ...                  ...
133805115        3  u13257688  click  2013-06-17 15:02:18
145624780        3   u6391967  click  2013-06-03 12:13:00
126681296        3   u2523719  click  2013-06-03 21:02:17
81514199         3   u1767882  click  2013-06-17 11:00:39
125793656        3  u12932287  click  2013-06-17 08:25:47

[500 rows x 4 columns]

In [25]:
sorted_action.to_csv('D:\\Datas\\datas\\action.csv', index=False)

## 3. 评论数据

In [26]:
import pandas as pd

chunk_size = 500000 # 每一块的行数
chunks_2 = []

for chunk in pd.read_csv('D:\\Datas\\tianchi_2014003_rec_tmall_review\\tianchi_2014003_rec_tmall_review.txt', sep="", chunksize=chunk_size):
    # 处理每个chunk的数据
    chunks_2.append(chunk)
    
# 合并chunk回一个大的DataFrame（如果需要的话）
review_1 = pd.concat(chunks_2, axis=0)

# 按照第一个字段进行排序
review_sorted = review_1.sort_values(by=review_1.columns[0])

# 将排序后的DataFrame转换为新的DataFrame
review = pd.DataFrame(review_sorted)

F:\Anaconda\procedure\lib\site-packages\IPython\core\interactiveshell.py:3364: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

In [40]:
import pandas as pd
from IPython.display import display, HTML

# 定义列名列表
column_names = ['item_id', 'rater_uid', 'feedback',' ','gmt_create']

# 设置DataFrame列名
review.columns = column_names

# 选择前10行数据
first_ten_rows = review.head(50)

# 为带滚动条的DataFrame横向展示设置CSS
styles = """
<style>
.scrollable_dataframe {
    max-height: 300px;
    overflow-x: auto;
    white-space: nowrap;
}
th {
    font-size: 14px;
}
td {
    font-size: 14px;
}
</style>
"""

# 生成带滚动条的DataFrame HTML
scrollable_df_html = f'<div class="scrollable_dataframe">{first_ten_rows.to_html()}</div>'

# 将CSS样式和HTML DataFrame包装在一起
html_output = styles + scrollable_df_html

# 在Jupyter Notebook中显示带滚动条的DataFrame
display(HTML(html_output))

In [36]:
#review.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11092203 entries, 6062285 to 524706
Data columns (total 5 columns):
 #   Column      Dtype
---  ------      -----
 0   item_id     int64
 1   rater_uid   object
 2   feedback    object
 3               object
 4   gmt_create  object
dtypes: int64(1), object(4)
memory usage: 507.8+ MB

In [41]:
sorted_review = review[(review['item_id'] >= 1) & (review['item_id'] <= 100000)]

In [42]:
sorted_review.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 136840 entries, 6062285 to 3934797
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   item_id     136840 non-null  int64
 1   rater_uid   136840 non-null  object
 2   feedback    136840 non-null  object
 3               0 non-null       object
 4   gmt_create  136840 non-null  object
dtypes: int64(1), object(4)
memory usage: 6.3+ MB

In [43]:
sorted_review.to_csv('D:\\Datas\\datas\\review.csv', index=False)

In [ ]:
import mysql.connector

# 连接到MySQL数据库
mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="296692",
    database="e-commerce_platform"
)

# 查询数据
mycursor = mydb.cursor()
mycursor.execute("SELECT * FROM review_sample")
result = mycursor.fetchall()

# 将数据转换为DataFrame
import pandas as pd
data = pd.DataFrame(result, columns=['ID','item_id','feedback','gmt_create','rate_pic_url'])
data.head(10)

In [ ]:
import pandas as pd


chunk_size = 500000 # 每一块的行数
chunks = []

for chunk in pd.read_csv('D:\\Datas\\datas\\review.csv', chunksize=chunk_size):
    # 处理每个chunk的数据
    chunks.append(chunk)
review = pd.concat(chunks, axis=0)
review.head(10)

In [ ]:
#查看每一列的缺失值
review.isnull().sum()

In [ ]:
#分词
import jieba
#返回生成器
def cut_word(text):
    return jieba.cut(text,cut_all=False)

    
review['review_cut'] = review['review'].apply(cut_word)
#停用词处理
def get_stopword():
    s = set()
    with open('哈工大停用词表.txt',encoding = 'UTF-8') as f:
        for line in f:
            s.add(line.strip())
    return s




def remove_stopword(words):
    return [word for word in words if word not in stopword]

stopword = get_stopword()
review['review_cut'] = review['review_cut'].apply(remove_stopword)
review.head()

In [ ]:
#统计出现频率最多的20个词
from itertools import chain
from collections import Counter

li_2d = review['review_cut'].tolist()
#将二维列表转换为一维
li_1d = list(chain.from_iterable(li_2d))
print(f'总词汇量：{len(li_1d)}')
c = Counter(li_1d)
print(f'不重复词汇量：{len(c)}')
common = c.most_common(20)
print(common)